services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-suscripciones
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: app-suscriptions-net
