export const dashboardStyles = {
  panel: "rounded-lg bg-panel-soft p-5 shadow-sm shadow-header-top/5 sm:p-6",
  panelShell: "rounded-lg bg-panel-soft shadow-sm shadow-header-top/5",
  accentPanel: "rounded-lg bg-accent-soft p-5 shadow-sm shadow-header-top/5 sm:p-6",
  summaryBadge: "flex max-w-full items-center gap-3 rounded-md border border-soft-border bg-white px-3 py-2.5 shadow-sm shadow-header-top/5 sm:max-w-xs",
  summaryIcon: "flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-accent-soft text-ink-teal",
  searchShell: "flex h-9 min-w-0 flex-1 items-center gap-2 rounded-md border border-soft-border bg-white px-2.5 shadow-sm shadow-header-top/5 focus-within:ring-2 focus-within:ring-header-accent",
  commandSearchShell: "flex h-11 items-center gap-2 rounded-md border border-soft-border bg-white px-3 shadow-sm shadow-header-top/5 transition-colors focus-within:border-table-header-text focus-within:ring-2 focus-within:ring-soft-focus",
  primaryAction: "inline-flex h-10 items-center justify-center gap-2 rounded-md bg-header-top px-4 text-sm font-semibold text-white shadow-sm shadow-header-top/20 transition-colors hover:bg-header-bg hover:text-white disabled:pointer-events-none disabled:opacity-60",
  softButton: "inline-flex h-9 items-center justify-center rounded-md border border-soft-border bg-white/80 px-3 text-sm font-semibold text-action-soft shadow-sm shadow-header-top/5 transition-colors hover:bg-white hover:text-ink-teal",
  subtleIconButton: "flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-muted transition-colors hover:bg-hover-soft hover:text-title",
  successNotice: "rounded-md bg-success-soft p-3 text-sm text-success-text-soft",
  tableHeader: "bg-hover-soft",
  pageSizeSelect: "h-9 border-soft-border bg-white",
  paginationPreviousEnabled: "border border-slate-border/50 bg-previous-soft text-slate-strong shadow-sm shadow-header-top/5 hover:border-slate-strong hover:bg-slate-strong hover:text-white",
  paginationPreviousDisabled: "pointer-events-none border border-slate-border/30 bg-disabled-soft text-slate-muted/60",
  paginationNextEnabled: "border border-action-teal/30 bg-next-soft text-action-teal shadow-sm shadow-action-teal/10 hover:border-action-teal-hover hover:bg-action-teal-hover hover:text-white",
  paginationNextDisabled: "pointer-events-none border border-soft-focus/70 bg-skeleton-muted text-table-header-text/55",
  editIconButton: "h-9 w-9 border-action-teal/30 bg-white text-action-teal shadow-sm shadow-action-teal/10 hover:border-action-teal hover:bg-action-teal-soft hover:text-action-teal-hover",
  dangerIconButton: "h-9 w-9 border-danger-action/25 bg-white text-danger-action-hover shadow-sm shadow-danger-action/10 hover:border-danger-action-hover hover:bg-danger-tint hover:text-danger-action-dark",
  dangerSmallIconButton: "h-8 w-8 shrink-0 border-danger-action/25 bg-white text-danger-action-hover shadow-sm shadow-danger-action/10 hover:border-danger-action-hover hover:bg-danger-tint hover:text-danger-action-dark",
  dangerAction: "border-danger-action bg-danger-action text-white hover:bg-danger-action-hover hover:text-white",
  selectedRow: "border-l-[3px] border-header-accent bg-white transition-colors",
  roleAdminBadge: "bg-provider-moabits-soft text-role-admin-text",
  roleManagerBadge: "bg-role-manager-soft text-role-manager-text",
} as const
