export const dashboardStyles = {
  panel: "rounded-lg bg-panel-soft p-5 shadow-sm shadow-header-top/5 sm:p-6",
  panelShell: "rounded-lg bg-panel-soft shadow-sm shadow-header-top/5",
  accentPanel: "rounded-lg bg-accent-soft p-5 shadow-sm shadow-header-top/5 sm:p-6",
  summaryBadge: "flex max-w-full items-center gap-3 rounded-md border border-soft-border bg-white px-3 py-2.5 shadow-sm shadow-header-top/5 sm:max-w-xs",
  summaryIcon: "flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-accent-soft text-ink-teal",
  searchShell: "flex h-9 min-w-0 flex-1 items-center gap-2 rounded-md border border-soft-border bg-white px-2.5 shadow-sm shadow-header-top/5 focus-within:ring-2 focus-within:ring-header-accent",
  commandSearchShell: "flex h-11 items-center gap-2 rounded-md border border-soft-border bg-white px-3 shadow-sm shadow-header-top/5 transition-colors focus-within:border-table-header-text focus-within:ring-2 focus-within:ring-soft-focus",
  primaryAction: "inline-flex h-10 items-center justify-center gap-2 rounded-md bg-header-top px-4 text-sm font-semibold text-white shadow-sm shadow-header-top/20 transition-colors hover:bg-header-bg hover:text-white disabled:pointer-events-none disabled:opacity-60",
  softButton: "inline-flex h-9 items-center justify-center rounded-md border border-soft-border bg-white/80 px-3 text-sm font-semibold text-action-soft shadow-sm shadow-header-top/5 transition-colors hover:bg-white hover:text-ink-teal",
  subtleIconButton: "flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-muted transition-colors hover:bg-hover-soft hover:text-title",
  successNotice: "rounded-md bg-success-soft p-3 text-sm text-success-text-soft",
  tableHeader: "bg-hover-soft",
  pageSizeSelect: "h-9 border-soft-border bg-white",
  paginationPreviousEnabled: "border border-[#94A3B8]/50 bg-previous-soft text-[#334155] shadow-sm shadow-header-top/5 hover:border-[#334155] hover:bg-[#334155] hover:text-white",
  paginationPreviousDisabled: "pointer-events-none border border-[#CBD5E1]/60 bg-[#EEF3F5] text-[#64748B]/60",
  paginationNextEnabled: "border border-[#0E7490]/30 bg-next-soft text-[#155E75] shadow-sm shadow-[#0891B2]/10 hover:border-[#155E75] hover:bg-[#155E75] hover:text-white",
  paginationNextDisabled: "pointer-events-none border border-[#B8DDE1]/70 bg-[#E3F1F2] text-table-header-text/55",
} as const
